# playbook.conf
# Security constraints & target OS schema for AME Wizard

[Requirements]
RequiresWindowsVersion=10.0
RequiresArchitecture=x64
RequiresAdminPrivileges=true
RequiresTrustedInstaller=true
RequiresVTx=true
RequiresIOMMU=true

[TargetSchema]
OS=Windows_10_11_latest
Architecture=x64
PrivilegeLevel=NT_AUTHORITY_SYSTEM

[Security]
Password=malte
Encryption=LZMA2
EncryptHeaders=true
