// AUTOGENERATED BY OUROBOROS 🐍 - DO NOT EDIT
#pragma pack(push, 1)
typedef struct _LLM_TENSOR_BLOCK {
    float q_proj[8192 * 4096];
    float k_proj[8192 * 4096];
    float v_proj[8192 * 4096];
    float o_proj[4096 * 8192];
} LLM_TENSOR_BLOCK;
#pragma pack(pop)
