# 03_HiveMind_Orchestrator/OpenMosix_2026/scripts/ouroboros_ast_gen.py
# Crucible: PATTERN-005 (Use pathlib)

import json
import os
import sys
from pathlib import Path


def generate_tensor_structs(schema_path: Path, output_path: Path) -> None:
    if not schema_path.exists():
        print(f"Schema not found: {schema_path}", file=sys.stderr)
        sys.exit(1)

    with schema_path.open() as f:
        schema = json.load(f)

    with output_path.open("w") as out:
        out.write("// AUTOGENERATED BY OUROBOROS 🐍 - DO NOT EDIT\n")
        out.write("#pragma pack(push, 1)\n")
        out.write("typedef struct _LLM_TENSOR_BLOCK {\n")
        for layer in schema.get('layers', []):
            out.write(f"    float {layer['name']}[{layer['dimensions']}];\n")
        out.write("} LLM_TENSOR_BLOCK;\n")
        out.write("#pragma pack(pop)\n")

if __name__ == "__main__":
    schema_file = Path(os.environ.get("SYMBIOSE_SCHEMA", "llm_schema.json"))
    out_file = Path(os.environ.get("SYMBIOSE_OUT", "generated_tensors.h"))
    generate_tensor_structs(schema_file, out_file)
