# # 03_HiveMind_Orchestrator/OpenMosix_2026/scripts/ouroboros_ast_gen.py
# Crucible: PATTERN-005 (Use pathlib)

import json
from pathlib import Path
import sys
import os


def generate_tensor_structs(schema_path: Path, output_path: Path) -> None:
    if not schema_path.exists():
        sys.exit(f"Schema not found: {schema_path}")

    # 🧪 ALCHEMIST: Consolidated I/O operations and context managers.
    # Reads entire JSON file and parses immediately, then uses a generator
    # expression and join to construct the C header in memory, writing it in
    # a single I/O system call via pathlib's write_text. Measurably faster.
    schema = json.loads(schema_path.read_text())

    output_path.write_text(
        "// AUTOGENERATED BY OUROBOROS 🐍 - DO NOT EDIT\n"
        "#pragma pack(push, 1)\n"
        "typedef struct _LLM_TENSOR_BLOCK {\n"
        + "".join(
            f"    float {layer['name']}[{layer['dimensions']}];\n"
            for layer in schema.get("layers", [])
        )
        + "} LLM_TENSOR_BLOCK;\n"
        "#pragma pack(pop)\n"
    )


if __name__ == "__main__":
    schema_file = Path(os.environ.get("SYMBIOSE_SCHEMA", "llm_schema.json"))
    out_file = Path(os.environ.get("SYMBIOSE_OUT", "generated_tensors.h"))
    generate_tensor_structs(schema_file, out_file)
