# 03_HiveMind_Orchestrator/OpenMosix_2026/scripts/ouroboros_ast_gen.py
# Crucible: PATTERN-005 (Use pathlib)

import json
import os
import sys
from pathlib import Path


def generate_tensor_structs(schema_path: Path, output_path: Path) -> None:
    if not schema_path.exists():
        sys.exit(f"Schema not found: {schema_path}")

    # 🧪 Alchemist Trick: File read/write combined with a generator expression
    # and f-strings for a single-pass, memory-efficient text generation pipeline.
    schema = json.loads(schema_path.read_text())
    fields = "".join(
        f"    float {layer['name']}[{layer['dimensions']}];\n"
        for layer in schema.get("layers", [])
    )

    output_path.write_text(
        "// AUTOGENERATED BY OUROBOROS 🐍 - DO NOT EDIT\n"
        "#pragma pack(push, 1)\n"
        "typedef struct _LLM_TENSOR_BLOCK {\n"
        f"{fields}"
        "} LLM_TENSOR_BLOCK;\n"
        "#pragma pack(pop)\n"
    )


if __name__ == "__main__":
    generate_tensor_structs(
        Path(os.getenv("SYMBIOSE_SCHEMA", "llm_schema.json")),
        Path(os.getenv("SYMBIOSE_OUT", "generated_tensors.h")),
    )
