/*++
 * trace.h — WPP Software Tracing Provider for SymbioseOS KMDF Hypervisor
 *
 * BRIDGE-000: WPP Tracing Setup
 * Reference: Interactive_Plan.md §III·1 (lines 830-843)
 *
 * Usage in .c files:
 *   #include "trace.h"
 *   #include "trace.tmh"   // Auto-generated by WPP preprocessor
 *
 * All debug output MUST use TraceEvents() — no DbgPrint.
 *
 * Provider GUID: {A1B2C3D4-E5F6-7890-ABCD-EF0123456789}
 * Capture command:
 *   tracelog.exe -start SymbioseSession -guid #A1B2C3D4-E5F6-7890-ABCD-EF0123456789 -f symbiose.etl
 *--*/

#pragma once

//
// SYMBIOSE_NO_WPP: When defined, all WPP tracing is stubbed out.
// Use this for CI builds where the WPP preprocessor is not available.
// The .tmh auto-generated headers are only needed when WPP is active.
//
#ifdef SYMBIOSE_NO_WPP

// Stub out all WPP macros to no-ops
#define WPP_CONTROL_GUIDS
#define WPP_INIT_TRACING(...)   ((void)0)
#define WPP_CLEANUP(...)        ((void)0)
#define TraceEvents(...)        ((void)0)

// No .tmh include needed — define the guard so #include "xxx.tmh" is skipped
#define SYMBIOSE_WPP_STUBBED 1

#else // Full WPP tracing (production WDK build)

//
// WPP Provider GUID and Trace Flags
//
// Each WPP_DEFINE_BIT defines a flag that can be individually enabled/disabled
// by the trace controller (tracelog.exe / WinDbg / TraceView).
//
// Flag bits:
//   TRACE_DRIVER = 0x00000001 — General driver lifecycle events
//   TRACE_VMX    = 0x00000002 — VMX operations (VMXON, VMLAUNCH, VM-Exit)
//   TRACE_IOCTL  = 0x00000004 — IOCTL dispatch and completion
//   TRACE_ACPI   = 0x00000008 — Power management and Death Rattle protocol
//   TRACE_EPT    = 0x00000010 — Extended Page Table construction/modification
//   TRACE_SHM    = 0x00000020 — Shared Memory ring buffer operations
//
#define WPP_CONTROL_GUIDS                                                    \
    WPP_DEFINE_CONTROL_GUID(SymbioseTraceGuid,                               \
        (A1B2C3D4, E5F6, 7890, AB, CD, EF, 01, 23, 45, 67, 89),             \
        WPP_DEFINE_BIT(TRACE_DRIVER)   /* bit 0 = 0x00000001 */              \
        WPP_DEFINE_BIT(TRACE_VMX)      /* bit 1 = 0x00000002 */              \
        WPP_DEFINE_BIT(TRACE_IOCTL)    /* bit 2 = 0x00000004 */              \
        WPP_DEFINE_BIT(TRACE_ACPI)     /* bit 3 = 0x00000008 */              \
        WPP_DEFINE_BIT(TRACE_EPT)      /* bit 4 = 0x00000010 */              \
        WPP_DEFINE_BIT(TRACE_SHM)      /* bit 5 = 0x00000020 */              \
    )

//
// WPP Macros for TraceEvents(Level, Flags, ...) pattern
//
// These macros enable the standard WPP pattern:
//   TraceEvents(TRACE_LEVEL_INFORMATION, TRACE_VMX, "VMXON result: %!STATUS!", status);
//
// WPP evaluates: is the flag enabled AND is the trace level >= requested level?
//
#define WPP_LEVEL_FLAGS_LOGGER(level, flags) \
    WPP_LEVEL_LOGGER(flags)

#define WPP_LEVEL_FLAGS_ENABLED(level, flags) \
    (WPP_LEVEL_ENABLED(flags) && \
     WPP_CONTROL(WPP_BIT_ ## flags).Level >= level)

//
// WPP Function Annotation
//
// begin_wpp config
// FUNC TraceEvents(LEVEL, FLAGS, MSG, ...);
// end_wpp
//

#endif // SYMBIOSE_NO_WPP

