title: Phase 1
actions:
  - !cmd:
      command: 'bcdedit /set testsigning on'
      runAs: TrustedInstaller
      expect: 0
      rollback: 'bcdedit /set testsigning off'

  - !registryValue:
      path: 'HKLM\SYSTEM\CurrentControlSet\Control\DeviceGuard'
      value: 'EnableVirtualizationBasedSecurity'
      data: '0'
      type: REG_DWORD
      runAs: TrustedInstaller
      rollback_value: '1'

  - !registryValue:
      path: 'HKLM\SYSTEM\CurrentControlSet\Control\DeviceGuard\Scenarios\HypervisorEnforcedCodeIntegrity'
      value: 'Enabled'
      data: '0'
      type: REG_DWORD
      runAs: TrustedInstaller
      rollback_value: '1'

  - !registryValue:
      path: 'HKLM\SYSTEM\CurrentControlSet\Control\DeviceGuard'
      value: 'HVCIMATRequired'
      data: '0'
      type: REG_DWORD
      runAs: TrustedInstaller
      rollback_value: '1'

  - !registryValue:
      path: 'HKLM\SYSTEM\CurrentControlSet\Control\Lsa'
      value: 'LsaCfgFlags'
      data: '0'
      type: REG_DWORD
      runAs: TrustedInstaller
      rollback_value: '1'

  - !registryValue:
      path: 'HKLM\SYSTEM\CurrentControlSet\Control\Lsa'
      value: 'RunAsPPL'
      data: '0'
      type: REG_DWORD
      runAs: TrustedInstaller
      rollback_value: '1'

  - !cmd:
      command: 'bcdedit /set disableelxservices on'
      runAs: TrustedInstaller
      expect: 0
      rollback: 'bcdedit /set disableelxservices off'
